-- Создание базы данных
CREATE DATABASE shop_db;

-- Создание таблицы с пользователями
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE'
);

-- Создание таблицы с ролями пользователей
CREATE TABLE roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE'
);

-- Создание связующей таблицы пользователей с их ролями
CREATE TABLE users_roles (
    user_id BIGINT,
    role_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Создание таблицы с категориями товаров
CREATE TABLE categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_category_id BIGINT,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE'
);

-- Создание таблицы с товарами
CREATE TABLE products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE'
);

-- Создание таблицы с изображениями к товарам
CREATE TABLE images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_data BYTEA NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Создание связующей таблицы товаров с категориями
CREATE TABLE categories_products (
    product_id BIGINT,
    category_id BIGINT,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Создание таблицы с заказами
CREATE TABLE orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(25) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Создание связующей таблицы товаров с заказами
CREATE TABLE products_orders (
    product_id BIGINT,
    order_id BIGINT,
    quantity INT,
    price DECIMAL(10, 2),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);